import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BiUserPlus } from "react-icons/bi";
import Table from "../components/Table";
import StudentForm from "../components/StudentForm";
import { useState } from "react";

export default function Home() {
  const [visible, setVisible] = useState(false);

  const handler = () => {
    setVisible(!visible);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Student Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Student Manager</h1>
        </div>
        <div className={styles.btnRow}>
          <button className={styles.addStudent} onClick={handler}>
            Add Student <BiUserPlus />
          </button>
        </div>
        {/* collapsable form */}
        <div className={styles.formContainer}>
          {visible ? <StudentForm /> : <></>}
        </div>
        <div className={styles.tableContainer}>
          <Table />
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>dbwebdev.io</span>
      </footer>
    </div>
  );
}
